from enum import Enum

class EventType(Enum):
    # Earnings & Revenue
    EARNINGS_BEAT = "EARNINGS_BEAT"
    EARNINGS_MISS = "EARNINGS_MISS"
    REVENUE_BEAT = "REVENUE_BEAT"
    REVENUE_MISS = "REVENUE_MISS"
    GUIDANCE_RAISE = "GUIDANCE_RAISE"
    GUIDANCE_CUT = "GUIDANCE_CUT"
    # M&A and Corporate Actions
    MA_ANNOUNCED = "MA_ANNOUNCED"
    MA_BLOCKED = "MA_BLOCKED"
    SPINOFF = "SPINOFF"
    STOCK_BUYBACK = "STOCK_BUYBACK"
    DIVIDEND_CUT = "DIVIDEND_CUT"
    DIVIDEND_HIKE = "DIVIDEND_HIKE"
    STOCK_SPLIT = "STOCK_SPLIT"
    # Regulatory & Legal
    FDA_APPROVAL = "FDA_APPROVAL"
    FDA_REJECTION = "FDA_REJECTION"
    REGULATORY_ACTION = "REGULATORY_ACTION"
    ANTITRUST = "ANTITRUST"
    PATENT_RULING = "PATENT_RULING"
    # Analyst Actions
    ANALYST_UPGRADE = "ANALYST_UPGRADE"
    ANALYST_DOWNGRADE = "ANALYST_DOWNGRADE"
    ANALYST_INITIATION = "ANALYST_INITIATION"
    # Leadership
    CEO_DEPARTURE = "CEO_DEPARTURE"
    CFO_DEPARTURE = "CFO_DEPARTURE"
    BOARD_SHAKEUP = "BOARD_SHAKEUP"
    # Insider Activity
    INSIDER_BUY = "INSIDER_BUY"
    INSIDER_SELL = "INSIDER_SELL"
    # Macro Events
    MACRO_CPI = "MACRO_CPI"
    MACRO_FOMC = "MACRO_FOMC"
    MACRO_NFP = "MACRO_NFP"
    MACRO_GDP = "MACRO_GDP"
    MACRO_PPI = "MACRO_PPI"
    MACRO_RETAIL_SALES = "MACRO_RETAIL_SALES"
    MACRO_HOUSING = "MACRO_HOUSING"
    MACRO_PMI = "MACRO_PMI"
    # Sector-Specific
    CHIP_EXPORT_CONTROL = "CHIP_EXPORT_CONTROL"
    OIL_PRODUCTION_CUT = "OIL_PRODUCTION_CUT"
    OIL_INVENTORY = "OIL_INVENTORY"
    PIPELINE_DISRUPTION = "PIPELINE_DISRUPTION"
    POWER_GRID_EVENT = "POWER_GRID_EVENT"
    DRUG_TRIAL_DATA = "DRUG_TRIAL_DATA"
    CYBER_BREACH = "CYBER_BREACH"
    SUPPLY_CHAIN_DISRUPTION = "SUPPLY_CHAIN_DISRUPTION"
    PRODUCT_RECALL = "PRODUCT_RECALL"
    CONTRACT_WIN = "CONTRACT_WIN"
    CONTRACT_LOSS = "CONTRACT_LOSS"
    # Distress
    BANKRUPTCY = "BANKRUPTCY"
    CREDIT_DOWNGRADE = "CREDIT_DOWNGRADE"
    CREDIT_UPGRADE = "CREDIT_UPGRADE"
    DEBT_DEFAULT = "DEBT_DEFAULT"
    # Special
    ACTIVIST_STAKE = "ACTIVIST_STAKE"
    SHORT_SQUEEZE = "SHORT_SQUEEZE"
    GEOPOLITICAL = "GEOPOLITICAL"
    TARIFF = "TARIFF"
    SANCTIONS = "SANCTIONS"
    NATURAL_DISASTER = "NATURAL_DISASTER"
    UNKNOWN = "UNKNOWN"

